# Generated by Django 3.2.6 on 2021-08-28 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2021, 8, 28, 5, 57, 40, 956679, tzinfo=utc))),
                ('blog', models.TextField()),
            ],
        ),
    ]
